import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

// ✅ Оптимизация: шрифт загружается локально, без layout shift
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Nextjs App',
	description: 'Generated by pacman',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className}  antialiased`}>{children}</body>
		</html>
	);
}
